### ISSUE TITLE
TESTES- synchronisation des Threads 

### ISSUE THREAD

**Issue by AndreeaChiurciu** [AndreeaChiurciu/facebooklike#11]

**Comment by ruxandra2000** [comment]
http://python.jpvweb.com/mesrecettespython/doku.php?id=thread_lock

**Comment by ruxandra2000** [comment]
import threading
import sys

x = 0
n = 1000

def fnadd() :
    global x,verrou
    for i in xrange(n) :
        verrou.acquire()
        x += 1
        verrou.release()

def fnsub() :
    global x,verrou
    for i in xrange(n) :
        verrou.acquire()
        x -= 1
        verrou.release()

verrou = threading.Lock()
t1=threading.Thread(target=fnadd)
t2=threading.Thread(target=fnsub)
t1.start()
t2.start()
t1.join()
t2.join()
print "Valeur finale de la variable x = ", x
