### ISSUE TITLE
Documentation sur le code en python pour le Facebook like button

### ISSUE THREAD

**Issue by AndreeaChiurciu** [AndreeaChiurciu/facebooklike#2]

**Comment by ruxandra2000** [comment]
import Tkinter
import tkMessageBox

top = Tkinter.Tk()

def helloCallBack():
   tkMessageBox.showinfo( "Like", "Thanks for liking our photo!")

B = Tkinter.Button(top, text ="Like", command = helloCallBack)

B.pack()
top.mainloop()

**Comment by ruxandra2000** [comment]
https://pypi.python.org/pypi/django-like-button/0.0.7

**Comment by ruxandra2000** [comment]
import Tkinter
import tkMessageBox

top = Tkinter.Tk()

def helloCallBack():
   tkMessageBox.showinfo( "Like", "Thanks for liking our photo!")

B = Tkinter.Button(top, text ="Like", command = helloCallBack)

B.pack()
top.mainloop()
