### ISSUE TITLE
CODE- comment traiter les parametres de la ligne de commande

### ISSUE THREAD

**Issue by AndreeaChiurciu** [AndreeaChiurciu/facebooklike#8]

**Comment by ruxandra2000** [comment]
http://openclassrooms.com/courses/apprenez-a-developper-en-c/la-ligne-de-commande-3
http://python.developpez.com/cours/DiveIntoPython/php/frdiveintopython/scripts_and_streams/command_line_arguments.php

**Comment by ruxandra2000** [comment]
def main(argv):  
    grammar = "kant.xml"  
    try:  
        opts, args = getopt.getopt(argv, "hg:d", ["help", "grammar="])
    except getopt.GetoptError:  
        usage()  
        sys.exit(2)  
    for opt, arg in opts:  
        if opt in ("-h", "--help"):  
            usage()  
            sys.exit()  
        elif opt == '-d':  
            global _debug  
            _debug = 1  
        elif opt in ("-g", "--grammar"): 
            grammar = arg               

source = "".join(args)               

k = KantGenerator(grammar, source)
    print k.output()
