### ISSUE TITLE
CODE- comment utiliser les Threads en python

### ISSUE THREAD

**Issue by AndreeaChiurciu** [AndreeaChiurciu/facebooklike#9]

**Comment by ruxandra2000** [comment]
def afficher_un_truc_regulierement(truc, delai, nombre):
    """Affiche un "truc" tous les "delais" un certain "nombre" de fois"""
    import time
    derniere_occur = time.time()
    num = 0
    while num &lt; nombre:
        maintenant = time.time()
        if maintenant - derniere_occur > delai:
            derniere_occur = maintenant
            print str(num) + " : " + truc
            num += 1
        yield     # Je rajoute mon(mes) yield(s) où je veux.

**Comment by ruxandra2000** [comment]
http://sametmax.com/concurrence-sans-threads-en-python/
